import { Dimensions, StyleSheet } from "react-native";
import {
  BACKGROUND,
  BLACK,
  ECHO_COLOR,
  ECHO_GLOW,
  ECHO_LIGHT,
  LIGHT_GRAY,
  MEDIUM_GRAY,
  SHADOW_MEDIUM,
  SHADOW_SOFT,
  SURFACE_CARD,
  SURFACE_LIGHT,
  SURFACE_MEDIUM,
  TEXT_SECONDARY,
  WHITE
} from "../constants/colors";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};
const BORDER_RADIUS = {
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 28,
  round: 999,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BACKGROUND,
    justifyContent: "center",
    alignItems: "center",
  },

  ///////////////////////////////////////STYLES FOR CONVERSATIONS PAGE
  searchContainer: { 
    position: "absolute", 
    top: SPACING.xxxl * 2 + SPACING.md,
    left: SPACING.xl, 
    right: SPACING.xl, 
    backgroundColor: SURFACE_MEDIUM, 
    borderRadius: BORDER_RADIUS.lg, 
    shadowColor: SHADOW_SOFT, 
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1, 
    shadowRadius: 12,
    elevation: 4, 
    paddingHorizontal: SPACING.lg, 
    paddingVertical: SPACING.sm,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  searchInput: {
    fontSize: 16,
    paddingVertical: SPACING.md,
    color: BLACK,
    fontWeight: "500",
  },
  conversationGrid: {
    paddingTop: 150,
    paddingBottom: 200,
    paddingHorizontal: SPACING.md,
  },
  row: {
    justifyContent: "space-between",
    marginBottom: SPACING.xl,
  },
  conversationSquare: { 
    width: (SCREEN_WIDTH - SPACING.xl * 2 - SPACING.md * 4) / 3, 
    height: (SCREEN_WIDTH - SPACING.xl * 2 - SPACING.md * 4) / 3,
    alignItems: "center", 
    justifyContent: "center", 
    backgroundColor: SURFACE_CARD, 
    marginHorizontal: SPACING.sm, 
    borderRadius: BORDER_RADIUS.xxl, 
    shadowColor: ECHO_GLOW, 
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4, 
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: BORDER_RADIUS.xxl,
  },
  conversationNameBadge: {
    position: "absolute",
    bottom: SPACING.sm,
    left: SPACING.md,
    right: SPACING.md,
    backgroundColor: SURFACE_LIGHT,
    borderRadius: BORDER_RADIUS.md,
    paddingVertical: SPACING.xs + 2,
    paddingHorizontal: SPACING.sm,
    zIndex: 10,
    shadowColor: SHADOW_SOFT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 0.5,
    borderColor: MEDIUM_GRAY,
  },
  conversationNameText: {
    fontSize: 11,
    fontWeight: "600",
    color: BLACK,
    textAlign: "center",
  },

  ///////////////////////////////////////// STYLES FOR CHAT PAGE
  chatContainer: {
    flex: 1,
    backgroundColor: BACKGROUND,
  },
  chatHeader: {
    position: "absolute",
    top: SPACING.xxxl + SPACING.sm,
    left: SCREEN_WIDTH * 0.15,
    right: SCREEN_WIDTH * 0.15,
    backgroundColor: SURFACE_MEDIUM,
    borderRadius: BORDER_RADIUS.xl,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: SHADOW_SOFT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 10,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  chatHeaderAvatar: {
    width: 32,
    height: 32,
    borderRadius: BORDER_RADIUS.md,
    marginRight: SPACING.md,
  },
  chatHeaderName: {
    fontSize: 16,
    fontWeight: "600",
    color: BLACK,
    flex: 1,
  },
  chatHeaderStatus: {
    alignItems: "center",
    justifyContent: "center",
  },
  statusDot: {
    fontSize: 16,
    color: ECHO_COLOR,
    fontWeight: "bold",
  },
  messagesContainer: {
    paddingTop: 140,
    paddingBottom: 220,
    paddingHorizontal: SPACING.xl,
  },
  messageBubble: {
    marginVertical: SPACING.sm,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    maxWidth: "75%",
    shadowColor: SHADOW_SOFT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
  },
  myMessage: {
    alignSelf: "flex-end",
    backgroundColor: ECHO_COLOR,
    borderWidth: 1,
    borderColor: ECHO_LIGHT,
  },
  theirMessage: {
    alignSelf: "flex-start",
    backgroundColor: SURFACE_CARD,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 20,
  },
  myMessageText: {
    color: WHITE,
    fontWeight: "500",
  },
  theirMessageText: {
    color: BLACK,
    fontWeight: "400",
  },

  messageMeta: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: SPACING.xs,
    gap: SPACING.sm,
  },

  timestampText: {
    fontSize: 11,
    color: TEXT_SECONDARY,
    fontWeight: "400",
  },

  readStatus: {
    fontSize: 11,
    color: TEXT_SECONDARY,
    fontWeight: "400",
  },

  ///////////////////////////////////////// STYLES FOR HOME PAGE
  homeContainer: {
    flex: 1,
    backgroundColor: BACKGROUND,
    paddingTop: SPACING.xxxl + SPACING.xl,
    paddingHorizontal: SPACING.xl,
  },
  scrollContent: {
    paddingBottom: 200,
  },
  headerContainer: {
    marginBottom: SPACING.xxxl,
  },
  welcomeText: {
    fontSize: 30,
    fontWeight: "700",
    color: ECHO_COLOR,
    marginBottom: SPACING.md,
    marginTop: SPACING.xl,
    letterSpacing: -0.5,
  },
  subtitleText: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    marginBottom: SPACING.xl,
    fontWeight: "400",
  },
  logoutButton: {
    backgroundColor: "#FF3B30",
    borderRadius: BORDER_RADIUS.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    alignSelf: 'flex-start',
    shadowColor: SHADOW_MEDIUM,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 3,
  },
  logoutButtonText: {
    color: WHITE,
    fontSize: 15,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: BLACK,
    marginBottom: SPACING.lg,
    letterSpacing: -0.3,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: SPACING.xxxl + SPACING.sm,
  },
  emptyText: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    fontStyle: 'italic',
  },
  notificationButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: SURFACE_CARD,
    borderRadius: BORDER_RADIUS.lg,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    shadowColor: SHADOW_SOFT,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  notificationProfileImage: {
    width: 52,
    height: 52,
    borderRadius: BORDER_RADIUS.xxl,
    marginRight: SPACING.lg,
    borderWidth: 2,
    borderColor: LIGHT_GRAY,
  },
  conversationInfo: {
    flex: 1,
    position: 'relative',
  },
  conversationName: {
    fontSize: 16,
    fontWeight: '600',
    color: BLACK,
    marginBottom: SPACING.xs,
  },
  lastMessage: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    flex: 1,
    fontWeight: "400",
  },
  unreadBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: ECHO_COLOR,
    borderRadius: BORDER_RADIUS.round,
    minWidth: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    shadowColor: ECHO_GLOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  unreadText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: '700',
  },

  //////////////////////////////////////// STYLES FOR PROFILE PAGE
  profilePicture: {
    borderRadius: BORDER_RADIUS.round,
    width: 120,
    height: 120,
    alignSelf: "center",
    marginBottom: SPACING.lg,
    shadowColor: SHADOW_MEDIUM,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 3,
    borderColor: WHITE,
  },
  pseudo: {
    textAlign: "center",
    fontSize: 26,
    fontWeight: "700",
    color: BLACK,
    letterSpacing: -0.5,
    marginBottom: SPACING.sm,
  },

  ///////////////////////////////////// STYLES FOR BOTTOM BAR
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: SURFACE_LIGHT,
    borderTopLeftRadius: BORDER_RADIUS.xxxl,
    borderTopRightRadius: BORDER_RADIUS.xxxl,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.xl,
    shadowColor: SHADOW_MEDIUM,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 8,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: MEDIUM_GRAY,
  },

  chatSection: {
    backgroundColor: LIGHT_GRAY,
    borderRadius: BORDER_RADIUS.xl,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: MEDIUM_GRAY,
  },
  chatInput: {
    fontSize: 16,
    color: BLACK,
    fontWeight: "400",
  },
  navBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 0,
    backgroundColor: "transparent",
    paddingHorizontal: SPACING.sm,
    paddingBottom: SPACING.sm,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: SPACING.sm,
  },
  navText: {
    color: ECHO_COLOR,
    fontSize: 15,
    fontWeight: "600",
  },
});
