import { StyleSheet } from "react-native";
import { BACKGROUND_GRAY, DARK_GRAY, ECHO_COLOR, LIGHT_GRAY, WHITE } from "../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BACKGROUND_GRAY,
    justifyContent: "center",
    alignItems: "center",
  },

  ///////////////////////////////////////STYLES FOR CONVERSATIONS PAGE
  searchContainer: { 
    position: "absolute", 
    top: 70, 
    left: 20, 
    right: 20, 
    backgroundColor: "rgba(255,255,255,0.9)", 
    borderRadius: 25, 
    shadowColor: WHITE, 
    shadowOpacity: 0.9, 
    elevation: 3, 
    paddingHorizontal: 15, 
    paddingVertical: 5, 
  },
  searchInput: {
    fontSize: 16,
    paddingVertical: 8,
    color: DARK_GRAY,
  },
  conversationGrid: {
    paddingTop: 150,
    paddingBottom: 180,
    paddingHorizontal: 10,
  },
  row: {
    justifyContent: "space-between",
    marginBottom: 20,
  },
  conversationSquare: { 
    width: 110, 
    height : 110,
    alignItems: "center", 
    justifyContent: "center", 
    backgroundColor: LIGHT_GRAY, 
    marginHorizontal: 8, 
    borderRadius: 25, 
    paddingTop: 0, 
    paddingBottom: 0, 
    shadowColor: "rgba(170, 255, 181, 1)", 
    shadowOffset: { height : 0, width : 0},
    shadowOpacity: 1, 
    shadowRadius: 5,
    elevation: 5,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 25,
  },
  conversationNameBadge: {
    position: "absolute",
    bottom: 8,
    left: 13,
    right: 13,
    opacity: 0.6,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
    zIndex: 10,
    shadowColor: WHITE,
    shadowOpacity: 0.6,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  conversationNameText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
  },

  ///////////////////////////////////////// STYLES FOR CHAT PAGE
  chatContainer: {
    flex: 1,
    backgroundColor: "rgba(245,250,245,0.9)",
  },
  chatHeader: {
    position: "absolute",
    top: 30,
    left: 100,
    right: 100,
    backgroundColor: "rgba(230,230,230,0.7)",
    borderRadius: 40,
    paddingVertical: 8,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: DARK_GRAY,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 10,
  },
  chatHeaderAvatar: {
    width: 30,
    height: 30,
    borderRadius: 10,
    marginRight: 12,
  },
  chatHeaderName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#666",
    flex: 1,
  },
  chatHeaderStatus: {
    alignItems: "center",
    justifyContent: "center",
  },
  statusDot: {
    fontSize: 20,
    color: ECHO_COLOR,
    fontWeight: "bold",
    shadowColor: ECHO_COLOR,
    shadowOpacity: 0.8,
    shadowRadius: 15,
  },
  messagesContainer: {
    paddingTop: 140,
    paddingBottom: 200,
    paddingHorizontal: 20,
  },
  messageBubble: {
    marginVertical: 8,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 30,
    maxWidth: "80%",
    shadowColor: WHITE,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 3,
  },
  myMessage: {
    alignSelf: "flex-end",
    opacity: 0.7,
    backgroundColor: ECHO_COLOR,
    shadowColor: "#888",
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  theirMessage: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(230,230,230,0.7)",
    shadowColor: WHITE,
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  messageText: {
    fontSize: 16,
    lineHeight: 20,
  },
  myMessageText: {
    color: WHITE,
    fontWeight: "500",
  },
  theirMessageText: {
    color: "rgba(60,60,60,0.9)",
  },

  messageMeta: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 4,
    gap: 8,
  },

  timestampText: {
    fontSize: 10,
    color: "#aaa",
  },

  readStatus: {
    fontSize: 10,
    color: "#aaa",
  },

  ///////////////////////////////////////// STYLES FOR HOME PAGE
  homeContainer: {
    flex: 1,
    backgroundColor: BACKGROUND_GRAY,
    paddingTop: 50,
    paddingHorizontal: 20,
  },
  scrollContent: {
    paddingBottom: 180,
  },
  headerContainer: {
    marginBottom: 30,
  },
  welcomeText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#4da678",
    marginBottom: 10,
    marginTop: 20,
  },
  subtitleText: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
  },
  logoutButton: {
    backgroundColor: "#ff6b6b",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
  },
  logoutButtonText: {
    color: WHITE,
    fontSize: 14,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
  },
  notificationButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginBottom: 12,
    shadowColor: "#fff",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 7,
    elevation: 3,
  },
  notificationProfileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
  },
  conversationInfo: {
    flex: 1,
    position: 'relative',
  },
  conversationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  lastMessage: {
    fontSize: 14,
    color: "#777",
    flex: 1,
  },
  unreadBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: ECHO_COLOR,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  unreadText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: 'bold',
  },

  //////////////////////////////////////// STYLES FOR PROFILE PAGE
  profilePicture: {
    borderRadius: 60,
    width: 120,
    height: 120,
    alignSelf: "center",
    marginBottom: 15,
  },
  pseudo: {
    textAlign: "center",
    fontSize: 30,
    fontWeight: "bold",
    color: "rgba(70,70,130,0.5)",
  },

  ///////////////////////////////////// STYLES FOR BOTTOM BAR
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 86, 20, 0.2)",
    borderTopLeftRadius: 42,
    borderTopRightRadius: 42,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingVertical: 12,
    paddingHorizontal: 20,
    shadowColor: "rgba(250, 250, 250, 0.2)", 
    shadowOpacity: 0.6, 
    shadowRadius: 3, 
    elevation: 0,
  },

  chatSection: {
    backgroundColor: "rgba(250,250,250,0.9)",
    borderRadius: 35,
    paddingHorizontal: 25,
    paddingVertical: 10,
    marginBottom: 13,
    shadowColor: "rgba(255, 255, 255, 0.6)", 
    shadowOpacity: 0.5, 
    shadowRadius: 3, 
    elevation: 5,
  },
  chatInput: {
    fontSize: 16,
    color: "#444",
  },
  navBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 0,
    backgroundColor: "rgba(70,70,130,0.)",
    borderRadius: 35,
    paddingHorizontal: 25,
    paddingBottom: 10,
    shadowColor: "rgba(250, 250, 250, 0.6)", 
    shadowOpacity: 0.5, 
    shadowRadius: 3, 
    elevation: 5,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
  },
  navText: {
    color: "rgba(240, 240, 240, 0.8)",
    fontSize: 16,
    fontWeight: "bold",
  },
});
